/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as QuestionBankRouteImport } from './routes/question-bank'
import { Route as ParticipantRouteImport } from './routes/participant'
import { Route as MyHistoryRouteImport } from './routes/my-history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as EvaluationsRouteImport } from './routes/evaluations'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AreasRouteImport } from './routes/areas'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TakeCodeRouteImport } from './routes/take.$code'
import { Route as MyResultsIdRouteImport } from './routes/my-results.$id'
import { Route as EvaluationResultsIdRouteImport } from './routes/evaluation-results.$id'
import { Route as EvaluationsIdResultsRouteImport } from './routes/evaluations.$id.results'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionBankRoute = QuestionBankRouteImport.update({
  id: '/question-bank',
  path: '/question-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantRoute = ParticipantRouteImport.update({
  id: '/participant',
  path: '/participant',
  getParentRoute: () => rootRouteImport,
} as any)
const MyHistoryRoute = MyHistoryRouteImport.update({
  id: '/my-history',
  path: '/my-history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationsRoute = EvaluationsRouteImport.update({
  id: '/evaluations',
  path: '/evaluations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasRoute = AreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TakeCodeRoute = TakeCodeRouteImport.update({
  id: '/take/$code',
  path: '/take/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const MyResultsIdRoute = MyResultsIdRouteImport.update({
  id: '/my-results/$id',
  path: '/my-results/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationResultsIdRoute = EvaluationResultsIdRouteImport.update({
  id: '/evaluation-results/$id',
  path: '/evaluation-results/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationsIdResultsRoute = EvaluationsIdResultsRouteImport.update({
  id: '/$id/results',
  path: '/$id/results',
  getParentRoute: () => EvaluationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/activity': typeof ActivityRoute
  '/areas': typeof AreasRoute
  '/dashboard': typeof DashboardRoute
  '/evaluations': typeof EvaluationsRouteWithChildren
  '/generate': typeof GenerateRoute
  '/login': typeof LoginRoute
  '/my-history': typeof MyHistoryRoute
  '/participant': typeof ParticipantRoute
  '/question-bank': typeof QuestionBankRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/users': typeof UsersRoute
  '/evaluation-results/$id': typeof EvaluationResultsIdRoute
  '/my-results/$id': typeof MyResultsIdRoute
  '/take/$code': typeof TakeCodeRoute
  '/evaluations/$id/results': typeof EvaluationsIdResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/activity': typeof ActivityRoute
  '/areas': typeof AreasRoute
  '/dashboard': typeof DashboardRoute
  '/evaluations': typeof EvaluationsRouteWithChildren
  '/generate': typeof GenerateRoute
  '/login': typeof LoginRoute
  '/my-history': typeof MyHistoryRoute
  '/participant': typeof ParticipantRoute
  '/question-bank': typeof QuestionBankRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/users': typeof UsersRoute
  '/evaluation-results/$id': typeof EvaluationResultsIdRoute
  '/my-results/$id': typeof MyResultsIdRoute
  '/take/$code': typeof TakeCodeRoute
  '/evaluations/$id/results': typeof EvaluationsIdResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/activity': typeof ActivityRoute
  '/areas': typeof AreasRoute
  '/dashboard': typeof DashboardRoute
  '/evaluations': typeof EvaluationsRouteWithChildren
  '/generate': typeof GenerateRoute
  '/login': typeof LoginRoute
  '/my-history': typeof MyHistoryRoute
  '/participant': typeof ParticipantRoute
  '/question-bank': typeof QuestionBankRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/users': typeof UsersRoute
  '/evaluation-results/$id': typeof EvaluationResultsIdRoute
  '/my-results/$id': typeof MyResultsIdRoute
  '/take/$code': typeof TakeCodeRoute
  '/evaluations/$id/results': typeof EvaluationsIdResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/activity'
    | '/areas'
    | '/dashboard'
    | '/evaluations'
    | '/generate'
    | '/login'
    | '/my-history'
    | '/participant'
    | '/question-bank'
    | '/results'
    | '/settings'
    | '/setup'
    | '/users'
    | '/evaluation-results/$id'
    | '/my-results/$id'
    | '/take/$code'
    | '/evaluations/$id/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/activity'
    | '/areas'
    | '/dashboard'
    | '/evaluations'
    | '/generate'
    | '/login'
    | '/my-history'
    | '/participant'
    | '/question-bank'
    | '/results'
    | '/settings'
    | '/setup'
    | '/users'
    | '/evaluation-results/$id'
    | '/my-results/$id'
    | '/take/$code'
    | '/evaluations/$id/results'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/activity'
    | '/areas'
    | '/dashboard'
    | '/evaluations'
    | '/generate'
    | '/login'
    | '/my-history'
    | '/participant'
    | '/question-bank'
    | '/results'
    | '/settings'
    | '/setup'
    | '/users'
    | '/evaluation-results/$id'
    | '/my-results/$id'
    | '/take/$code'
    | '/evaluations/$id/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ActivityRoute: typeof ActivityRoute
  AreasRoute: typeof AreasRoute
  DashboardRoute: typeof DashboardRoute
  EvaluationsRoute: typeof EvaluationsRouteWithChildren
  GenerateRoute: typeof GenerateRoute
  LoginRoute: typeof LoginRoute
  MyHistoryRoute: typeof MyHistoryRoute
  ParticipantRoute: typeof ParticipantRoute
  QuestionBankRoute: typeof QuestionBankRoute
  ResultsRoute: typeof ResultsRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  UsersRoute: typeof UsersRoute
  EvaluationResultsIdRoute: typeof EvaluationResultsIdRoute
  MyResultsIdRoute: typeof MyResultsIdRoute
  TakeCodeRoute: typeof TakeCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question-bank': {
      id: '/question-bank'
      path: '/question-bank'
      fullPath: '/question-bank'
      preLoaderRoute: typeof QuestionBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participant': {
      id: '/participant'
      path: '/participant'
      fullPath: '/participant'
      preLoaderRoute: typeof ParticipantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-history': {
      id: '/my-history'
      path: '/my-history'
      fullPath: '/my-history'
      preLoaderRoute: typeof MyHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluations': {
      id: '/evaluations'
      path: '/evaluations'
      fullPath: '/evaluations'
      preLoaderRoute: typeof EvaluationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas': {
      id: '/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/take/$code': {
      id: '/take/$code'
      path: '/take/$code'
      fullPath: '/take/$code'
      preLoaderRoute: typeof TakeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-results/$id': {
      id: '/my-results/$id'
      path: '/my-results/$id'
      fullPath: '/my-results/$id'
      preLoaderRoute: typeof MyResultsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation-results/$id': {
      id: '/evaluation-results/$id'
      path: '/evaluation-results/$id'
      fullPath: '/evaluation-results/$id'
      preLoaderRoute: typeof EvaluationResultsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluations/$id/results': {
      id: '/evaluations/$id/results'
      path: '/$id/results'
      fullPath: '/evaluations/$id/results'
      preLoaderRoute: typeof EvaluationsIdResultsRouteImport
      parentRoute: typeof EvaluationsRoute
    }
  }
}

interface EvaluationsRouteChildren {
  EvaluationsIdResultsRoute: typeof EvaluationsIdResultsRoute
}

const EvaluationsRouteChildren: EvaluationsRouteChildren = {
  EvaluationsIdResultsRoute: EvaluationsIdResultsRoute,
}

const EvaluationsRouteWithChildren = EvaluationsRoute._addFileChildren(
  EvaluationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ActivityRoute: ActivityRoute,
  AreasRoute: AreasRoute,
  DashboardRoute: DashboardRoute,
  EvaluationsRoute: EvaluationsRouteWithChildren,
  GenerateRoute: GenerateRoute,
  LoginRoute: LoginRoute,
  MyHistoryRoute: MyHistoryRoute,
  ParticipantRoute: ParticipantRoute,
  QuestionBankRoute: QuestionBankRoute,
  ResultsRoute: ResultsRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  UsersRoute: UsersRoute,
  EvaluationResultsIdRoute: EvaluationResultsIdRoute,
  MyResultsIdRoute: MyResultsIdRoute,
  TakeCodeRoute: TakeCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
